fogstreamtest/fogstreamtest/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls', namespace='mainapp')),
]

fogstreamtest/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.index, name='index'),
    path('register', mainapp.UserCreateView.as_view(), name='register_user'),
    path('login', mainapp.UserSignIn.as_view(), name='login'),
    path('logout', mainapp.user_logout, name='logout'),
    path('message', mainapp.MessageCreateView.as_view(), name='send_message')
]

fogstreamtest/mainapp/models.py
from django.db import models
import urllib.request

from mainapp.tasks import send_message


class Message(models.Model):
    STATUSES = [
        ('SC', 'Successfully'),
        ('US', 'Unsuccessfully'),
    ]

    email = models.EmailField(max_length=254)
    message = models.TextField()
    status = models.CharField(max_length=2, choices=STATUSES, default='US')

    def __str__(self):
        return f'{self.email} - {self.status}'

    def save(self, *args, **kwargs):
        create_task = False
        if self.pk is None:
            create_task = True
        super().save(*args, **kwargs)
        if create_task:
            send_message(self)


    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

fogstreamtest/mainapp/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from mainapp.models import Message
import django.forms as forms


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('email', 'message')

    def clean_email(self):
        data = self.cleaned_data['email']
        if data == '':
            raise forms.ValidationError('Введите email')
        user = User.objects.filter(email=data).first()
        if user is None:
            raise forms.ValidationError('Пользователя с таким email не существует')
        return data

    def clean_message(self):
        data = self.cleaned_data['message']
        if data == '':
            raise forms.ValidationError('Введите сообщение')
        return data

fogstreamtest/mainapp/views.py
from django.shortcuts import render, HttpResponseRedirect

from django.contrib.auth.forms import AuthenticationForm
from mainapp.forms import UserRegisterForm
from mainapp.forms import MessageForm
from django.urls import reverse_lazy

from django.contrib.auth.models import User
from mainapp.models import Message

from django.urls import reverse

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import user_passes_test

from django.http import JsonResponse

from django.views.generic.edit import CreateView, FormView

from django.utils.decorators import method_decorator

from django.conf import settings


class AjaxableResponseMixin:
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """

    def form_invalid(self, form):
        response = super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
            }
            return JsonResponse(data)
        else:
            return response


class UserCreateView(AjaxableResponseMixin, CreateView):
    model = User
    success_url = reverse_lazy('mainapp:login')
    form_class = UserRegisterForm


class UserSignIn(AjaxableResponseMixin, FormView):
    form_class = AuthenticationForm
    template_name = 'mainapp/login.html'
    success_url = reverse_lazy('mainapp:send_message')

    def form_valid(self, form):
        user = authenticate(**form.cleaned_data)
        if user:
            login(self.request, user)
        return HttpResponseRedirect(reverse_lazy('mainapp:send_message'))


def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('mainapp:send_message'))
    else:
        return HttpResponseRedirect(reverse('mainapp:login'))


@method_decorator(user_passes_test(lambda u: u.is_authenticated), name='dispatch')
class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('mainapp:send_message')
    template_name = 'mainapp/message.html'


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('mainapp:index'))

fogstreamtest/mainapp/templates/mainapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Тест на должность стажера Python/Django{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<ul>
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'mainapp:send_message' %}">Отправить сообщение</a>
    </li>
    <li>
        <a href="{% url 'mainapp:logout' %}">Выйти</a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'mainapp:login' %}">Войти</a>
    </li>
    <li>
        <a href="{% url 'mainapp:register_user' %}">Регистрация</a>
    </li>
    {% endif %}
</ul>
{% block content %}
{% endblock %}
</body>
</html>

fogstreamtest/mainapp/templates/mainapp/login.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
Вход
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Войти">
</form>
<a href="{% url 'mainapp:register_user' %}">
    Зарегистрироваться
</a>
{% endblock %}

fogstreamtest/mainapp/templates/mainapp/message.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block title %}
Отправить сообщение
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>
{% endblock %}